# src/config/settings.yaml
spark:
  app_name: "Analise de Pedidos"

paths:
  clientes: "./data-engineering-pyspark/data/input/dataset-json-clientes/data/clientes.json.gz"
  pedidos: "./data-engineering-pyspark/data/input/datasets-csv-pedidos/data/pedidos/"
  output: "./data-engineering-pyspark/data/output/pedidos_por_cliente"

file_options:
  pedidos_csv:
    compression: "gzip"
    header: True
    sep: ";"
    